/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ctash.sandbox.static_mocks;

import mockit.Mock;
import mockit.MockUp;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import static org.junit.jupiter.api.Assertions.assertEquals;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class AppTest {
    private App classUnderTest;

    @BeforeEach
    public void setupTest() {
        classUnderTest = new App();
    }

    @AfterEach
    public void tearDown() { }

    @Test
    @Order(1)
    public void testNonMockedStatic() {
        assertEquals(App.TEST_STRING, classUnderTest.getTestString(), "testString should equal non-mocked value");
    }

    @Test
    @Order(2)
    public void testStaticMocking() {
        new MockUp<App>() {
            @Mock
            public String getStaticTestString() {
                return "123";
            }
        };

        assertEquals("123", classUnderTest.getTestString(), "testString overriden to \"123\"");
    }

    /**
     * due to an apparent bug w/Jmockit's auto-teardown functionality
     * this fails because test 2's mock is not torn down
     */
    @Test
    @Order(3)
    public void testNonMockedStaticWillFail() {
        assertEquals(App.TEST_STRING, classUnderTest.getTestString(), "testString should equal non-mocked value");
    }
}
